name: "InferSharp-AzurePipelinesExample-Multistage"

jobs:
# Example of existing build pipeline
- job: RunExistingBuildPipeline
  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  # Build
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: Examples/Examples.sln

  - task: InferSharp@1
    inputs:
      TargetDirectory: '$(Build.SourcesDirectory)'
  
  - task: PublishSecurityAnalysisLogs@3
    inputs:
      ArtifactName: 'CodeAnalysisLogs'
      ArtifactType: 'Container'
      PublishProcessedResults: true
      AllTools: true
      ToolLogsNotFoundAction: 'Standard'

  - task: SdtReport@2
    inputs:
      GdnExportAllTools: true